# Generated by Django 5.0.9 on 2026-08-06 16:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Vai para o JSON como `id`. Não mude depois de publicado: ele aparece no payload da venda enviado ao n8n.', max_length=40, unique=True, verbose_name='identificador')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('descricao', models.CharField(blank=True, default='', max_length=240, verbose_name='descrição')),
                ('icone', models.CharField(default='diamond', help_text='Nome de um Material Symbol.', max_length=60, verbose_name='ícone')),
                ('cor', models.CharField(choices=[('gold', 'Dourado'), ('blue', 'Azul'), ('green', 'Verde'), ('purple', 'Roxo')], default='gold', max_length=10, verbose_name='cor')),
                ('travada', models.BooleanField(default=False, help_text='Aparece no lobby, mas não abre. Vai ao JSON como `locked`.', verbose_name='em implementação')),
                ('fluxo', models.CharField(blank=True, default='', help_text="Vazio = fluxo padrão (escolher produto da tabela). 'apn' = o consultor informa o valor da venda, sem tabela de preços. Categoria com fluxo próprio é somente leitura: não se edita pelo /admin.", max_length=20, verbose_name='fluxo próprio')),
                ('sigla', models.CharField(blank=True, default='', help_text='Só usada em categoria de fluxo próprio, onde não há produto para tirar a sigla do protocolo da venda.', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Use exatamente 3 letras maiúsculas.')], verbose_name='sigla')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ('ordem', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, verbose_name='identificador')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('sigla', models.CharField(help_text='Alimenta o protocolo da venda (SSS-YYMMDDPRRRRR).', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Use exatamente 3 letras maiúsculas.')], verbose_name='sigla')),
                ('descricao', models.CharField(blank=True, default='', max_length=240, verbose_name='descrição')),
                ('duracao', models.CharField(blank=True, default='', help_text="Texto de exibição ('12 meses', '3 dias'). Nunca é interpretado — quem manda no cálculo é `vigencia_meses`.", max_length=40, verbose_name='duração')),
                ('icone', models.CharField(default='workspace_premium', max_length=60, verbose_name='ícone')),
                ('recorrente', models.BooleanField(default=False, help_text='Recorrente: cobra mensalidade e o total é derivado. Avulso: valor único à vista.', verbose_name='recorrente')),
                ('mensalidade', models.DecimalField(blank=True, decimal_places=2, help_text='Só em produto recorrente.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('10000000'))], verbose_name='mensalidade')),
                ('vigencia_meses', models.PositiveSmallIntegerField(blank=True, help_text='Só em produto recorrente.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='vigência (meses)')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Só em produto avulso. Em recorrente o total é calculado, nunca digitado — por isso esta coluna fica nula lá.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100000000'))], verbose_name='valor à vista')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(help_text='PROTECT de propósito: produto já vendido não pode sumir do catálogo e deixar protocolos órfãos.', on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.categoria', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ('categoria', 'ordem', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PublicacaoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicado_em', models.DateTimeField(auto_now_add=True, verbose_name='publicado em')),
                ('autor_email', models.EmailField(blank=True, default='', help_text='Cópia do e-mail no momento da publicação. Guardado à parte porque a conta pode ser desativada depois, e o histórico não pode perder o nome de quem assinou a mudança.', max_length=254, verbose_name='e-mail do autor')),
                ('catalogo', models.JSONField(help_text='O JSON exatamente como foi servido depois desta publicação.', verbose_name='catálogo publicado')),
                ('resumo', models.TextField(blank=True, default='', help_text='O que mudou em relação à publicação anterior, em texto.', verbose_name='resumo das alterações')),
                ('autor', models.ForeignKey(blank=True, help_text='Nulo só para a semente inicial, que não tem autor humano.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes_catalogo', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'publicação do catálogo',
                'verbose_name_plural': 'publicações do catálogo',
                'ordering': ('-publicado_em',),
            },
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('categoria', 'slug'), name='produto_slug_unico_na_categoria'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(check=models.Q(('recorrente', False), models.Q(('mensalidade__isnull', False), ('recorrente', True), ('valor__isnull', True), ('vigencia_meses__isnull', False)), _connector='OR'), name='produto_recorrente_tem_mensalidade_e_vigencia'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(check=models.Q(('recorrente', True), models.Q(('mensalidade__isnull', True), ('recorrente', False), ('valor__isnull', False), ('vigencia_meses__isnull', True)), _connector='OR'), name='produto_avulso_tem_valor'),
        ),
    ]
