"""
Um PRODUTO passa a poder ter fluxo próprio — e, com ele, nenhum preço.

O QUE JÁ EXISTIA, E POR QUE NÃO SERVIA

`Categoria.fluxo` (a APN) tira a tabela de preços da categoria INTEIRA: lá não
há produto a escolher, o consultor informa o valor e pronto. Isso não serve para
a categoria "Produtos", que nasce agora com o Recrutamento e Seleção e vai
receber outros itens sem relação entre si — o próximo pode perfeitamente ser um
produto de tabela. Um fluxo na categoria trancaria todos no mesmo formulário.

Daí o campo aqui: a categoria segue listando produtos, e é o produto ESCOLHIDO
que decide para onde o consultor vai.

AS CONSTRAINTS

As duas antigas ganham um `~Q(fluxo="")` na frente, e entra uma terceira. Juntas
elas dizem: um produto é recorrente, ou avulso, ou de formulário — e cada um tem
exatamente um conjunto de colunas preenchido. Sem a terceira, um produto de
formulário poderia carregar um preço parado que ninguém lê e que alguém acaba
cotando; ela é o que garante que "sem preço" significa sem preço.

Migração só de schema: nenhuma linha existente tem `fluxo`, então nada muda de
comportamento até a `0010` criar o primeiro produto de formulário.
"""
# Generated by Django 6.1 on 2026-08-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_base_antes_do_pre'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='produto',
            name='produto_recorrente_tem_mensalidade_e_vigencia',
        ),
        migrations.RemoveConstraint(
            model_name='produto',
            name='produto_avulso_tem_valor',
        ),
        migrations.AddField(
            model_name='produto',
            name='fluxo',
            field=models.CharField(blank=True, choices=[('dh', 'Formulário DH (Recrutamento e Seleção)')], default='', help_text='Vazio = produto de tabela: tem preço aqui e o consultor segue o fluxo padrão. Preenchido, o produto NÃO tem preço — o consultor cai num formulário próprio e os valores saem de lá. Produto assim é somente leitura para a tela da diretoria.', max_length=20, verbose_name='fluxo próprio'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fluxo', ''), _negated=True), ('recorrente', False), models.Q(('mensalidade__isnull', False), ('recorrente', True), ('valor__isnull', True), ('vigencia_meses__isnull', False)), _connector='OR'), name='produto_recorrente_tem_mensalidade_e_vigencia'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fluxo', ''), _negated=True), ('recorrente', True), models.Q(('mensalidade__isnull', True), ('recorrente', False), ('valor__isnull', False), ('vigencia_meses__isnull', True)), _connector='OR'), name='produto_avulso_tem_valor'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('fluxo', ''), models.Q(('mensalidade__isnull', True), ('recorrente', False), ('valor__isnull', True), ('vigencia_meses__isnull', True)), _connector='OR'), name='produto_de_fluxo_proprio_nao_tem_preco'),
        ),
    ]
