# Generated by Django 5.0.9 on 2026-08-06 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoIdentidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidade_id', models.UUIDField(db_index=True, help_text='Casa por este UUID antes do e-mail: o e-mail muda, o UUID não.', unique=True, verbose_name='identidade no Conecta ID')),
                ('papel', models.CharField(blank=True, choices=[('gerente', 'Gerente — autoriza negociação'), ('diretoria', 'Diretoria — autoriza negociação e publica a tabela')], default='', help_text='Vazio = entra, mas não autoriza nada. A diretoria promove.', max_length=20, verbose_name='papel')),
                ('precisa_trocar_senha', models.BooleanField(default=False, help_text='Cópia local do que o Conecta ID informou no último login. Quem define senha é o Conecta ID, não este app.', verbose_name='precisa trocar a senha')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_identidade', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'vínculo de identidade',
                'verbose_name_plural': 'vínculos de identidade',
                'ordering': ('usuario__email',),
            },
        ),
    ]
