# Generated by Django 6.1 on 2026-10-01 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='O código que a fonte dá à categoria. É o que vai no payload da venda.', max_length=40, unique=True, verbose_name='código na fonte')),
                ('descricao', models.CharField(max_length=120, verbose_name='descrição')),
                ('ativo', models.BooleanField(db_index=True, default=True, help_text='Falso quando a fonte a marca como inativa ou deixa de listá-la.', verbose_name='ativo')),
                ('visto_em', models.DateTimeField(help_text='Última sincronização bem-sucedida que a listou, ativa ou não.', verbose_name='visto na fonte em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, help_text='Última mudança de nome ou de estado — não a última sincronização.', verbose_name='alterado em')),
            ],
            options={
                'verbose_name': 'categoria financeira',
                'verbose_name_plural': 'categorias financeiras',
                'ordering': ('descricao', 'codigo'),
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoCategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('lista', 'lista completa'), ('fixo', 'categoria fixa')], max_length=10, verbose_name='modo')),
                ('autor_email', models.EmailField(blank=True, default='', help_text='Cópia do e-mail no momento da gravação: a conta pode ser desativada depois, e o registro não pode perder quem decidiu.', max_length=254, verbose_name='e-mail do autor')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='gravado em')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_categoria_financeira', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('categoria', models.ForeignKey(blank=True, help_text='Só no modo fixo. Categoria nunca é apagada (ver o cabeçalho), então o PROTECT não deveria disparar nunca.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuracoes', to='categorias_financeiras.categoriafinanceira', verbose_name='categoria fixa')),
            ],
            options={
                'verbose_name': 'configuração da categoria financeira',
                'verbose_name_plural': 'configurações da categoria financeira',
                'ordering': ('-criado_em', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('categoria__isnull', True), ('modo', 'lista')), models.Q(('categoria__isnull', False), ('modo', 'fixo')), _connector='OR'), name='categoria_financeira_so_no_modo_fixo')],
            },
        ),
    ]
