# Generated by Django 6.1 on 2026-09-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='O `codigo` do ListarDepartamentos. É o que o n8n repassa ao Omie.', max_length=20, unique=True, verbose_name='código no Omie')),
                ('descricao', models.CharField(max_length=120, verbose_name='descrição')),
                ('estrutura', models.CharField(blank=True, default='', help_text='Posição na árvore do Omie (ex.: 001.003). É o que ordena a lista.', max_length=60, verbose_name='estrutura')),
                ('ativo', models.BooleanField(db_index=True, default=True, help_text='Falso quando o Omie o marca como inativo ou deixa de listá-lo.', verbose_name='ativo')),
                ('visto_em', models.DateTimeField(help_text='Última sincronização bem-sucedida que o listou, ativo ou não.', verbose_name='visto no Omie em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, help_text='Última mudança de nome, estrutura ou estado — não a última sincronização.', verbose_name='alterado em')),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'ordering': ('estrutura', 'descricao', 'codigo'),
            },
        ),
    ]
