# Generated by Django 6.1 on 2026-09-17 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('lista', 'lista completa'), ('fixo', 'departamento fixo')], max_length=10, verbose_name='modo')),
                ('autor_email', models.EmailField(blank=True, default='', help_text='Cópia do e-mail no momento da gravação: a conta pode ser desativada depois, e o registro não pode perder quem decidiu.', max_length=254, verbose_name='e-mail do autor')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='gravado em')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_departamento', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('departamento', models.ForeignKey(blank=True, help_text='Só no modo fixo. Departamento nunca é apagado (ver o cabeçalho), então o PROTECT não deveria disparar nunca.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuracoes', to='departamentos.departamento', verbose_name='departamento fixo')),
            ],
            options={
                'verbose_name': 'configuração do departamento',
                'verbose_name_plural': 'configurações do departamento',
                'ordering': ('-criado_em', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('departamento__isnull', True), ('modo', 'lista')), models.Q(('departamento__isnull', False), ('modo', 'fixo')), _connector='OR'), name='departamento_so_no_modo_fixo')],
            },
        ),
    ]
