# Generated by Django 5.0.9 on 2026-08-07 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprovanteVenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protocolo', models.CharField(db_index=True, help_text='O código da venda gerado no cliente (SSS-YYMMDDPRRRRR).', max_length=40, verbose_name='protocolo')),
                ('fluxo', models.CharField(choices=[('elite', 'Elite (produto de tabela)'), ('apn', 'APN (valor livre)')], max_length=10, verbose_name='fluxo')),
                ('negociado', models.BooleanField(default=False, help_text='Falso = preço de tabela. Verdadeiro exigiu autorização.', verbose_name='valores negociados')),
                ('valores', models.JSONField(verbose_name='valores atestados')),
                ('hash_valores', models.CharField(db_index=True, max_length=64, verbose_name='hash dos valores')),
                ('autorizador_email', models.EmailField(blank=True, default='', help_text='Cópia no momento da emissão — a conta pode ser desativada depois, e o histórico não pode perder o nome de quem assinou.', max_length=254, verbose_name='e-mail de quem autorizou')),
                ('emitido_em', models.DateTimeField(auto_now_add=True, verbose_name='emitido em')),
                ('expira_em', models.DateTimeField(db_index=True, verbose_name='expira em')),
                ('consumido_em', models.DateTimeField(blank=True, null=True, verbose_name='consumido em')),
                ('ip_emissao', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP na emissão')),
                ('autorizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprovantes_autorizados', to=settings.AUTH_USER_MODEL, verbose_name='quem autorizou')),
            ],
            options={
                'verbose_name': 'comprovante de venda',
                'verbose_name_plural': 'comprovantes de venda',
                'ordering': ('-emitido_em',),
                'indexes': [models.Index(fields=['consumido_em', 'expira_em'], name='vendas_comp_consumi_ab1984_idx')],
            },
        ),
    ]
