# Generated by Django 6.1 on 2026-08-25 14:21

"""
O comprovante passa a conhecer um terceiro fluxo: o DH.

Só `choices` — nenhuma coluna muda de forma, nenhum dado é reescrito. Está aqui
porque `choices` faz parte do estado que o Django versiona: sem a migração, todo
`makemigrations` seguinte geraria esta mesma alteração de novo, e a próxima
pessoa acharia que tem migração pendente sem saber de quê.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprovantevenda',
            name='fluxo',
            field=models.CharField(choices=[('elite', 'Elite (produto de tabela)'), ('apn', 'APN (valor livre)'), ('dh', 'DH (valores do formulário)')], max_length=10, verbose_name='fluxo'),
        ),
    ]
